/*!
 * Generated by ActivePresenter 5.5.4 HTML5 (2016.01.12)
 */
﻿/*!
 * Atomi HTML5 Player - Template parameters
 * Copyright (c) Atomi Systems, Inc. All rights reserved.
 * http://atomisystems.com
 * Created: 2008/01/20
 * Modified: 2013/11/01
 */

var PrezInfo = {
	Name:"DataDomain",
	Description:"",
	Date1: "5/25/2016",
	Author:"Niels",
	Copyright:"",
	Homepage:"",
	RLVersion: "5.5.5",
	AppHomePage: "http://atomisystems.com",
	ViewPort: {width:1366, height:768},
	Language: "en",
	TextDir: "ltr",
	Generator: "ActivePresenter 5.5.5"
};

var Options = {"opmodes":2,"language_id":60,"report_format":0,"report_value":"","pass_condition":0,"zoom_percent":100,"ShowReport":false,"ExportHTML5":true,"UseFlashPlayer":true,"pass_value":80,"report_method":0,"FlashABSpeed":0,"AllowNavigate":false,"test_max_time":0,"UseSilverlight":false,"image_format":"png","ConfirmRestart":false,"HilightFocus":true,"UseAccText":true,"ScormScorePercent":false};
var TemplateParams = {
   IniVolume:0,
   IniCCShow:0,
   HighLevelStepText:1,
   SlideListPos:2,
   ShowDuration:0,
   ShowSlideAsGroup:0,
   ToolbarHeight:28,
   ImagePath:"player/images/",
   IniSlideNotesShow:0,
   AlwaysShowSlideNotes:0,
   SlideNotesPos:2,
   IniAutoFit:1,
   ShowDetailedStepsInPractice:1,
   AlwaysShowSlideList:0,
   IniSlideListShow:0,
   DockPaneSize:0,
   NavInPractice:1
}
;
var bSendToLMS = false;
 
var PlayModes = {
	DEMO:	1,
	TUT:	2,
	PRAC:	4,
	TEST:	8
};

var UIPos = {
	//These correspond to value list in manifest
	TOP: 0,
	LEFT: 1,
	RIGHT: 2,
	BOTTOM: 3,
	FLOATING: 4,
	NONE: 5
};